import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth"; // Import nécessaire
import { authOptions } from "@/lib/auth";     // Import de ta config
import LogoutButton from "@/components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ink'App",
  description: "Generated by create next app",
};

// Le layout devient ASYNC pour récupérer la session
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Récupération de la session côté serveur
  const session = await getServerSession(authOptions);

  return (
    <html lang="fr">
      <body className={`${inter.className} bg-background text-foreground min-h-screen flex flex-col`}>
        
        {/* --- NAVBAR --- */}
        <nav className="border-b border-border bg-white dark:bg-slate-950 sticky top-0 z-10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 justify-between items-center">
              <div className="flex gap-8 items-center">
                <Link href="/" className="text-xl font-bold text-primary">
                  📦 InkStock
                </Link>
                <div className="hidden md:flex gap-6 text-sm font-medium">
                  <Link href="/catalogue" className="hover:text-primary transition">Catalogue</Link>
                  <Link href="/mouvements" className="hover:text-primary transition">Historique</Link>
                </div>
              </div>
              
              <div className="flex items-center gap-4">
                {session?.user ? (
                  // Conteneur Flex pour aligner Texte + Bouton Logout
                  <div className="flex items-center gap-3 mr-2 border-r border-border pr-4">
                    <div className="hidden sm:flex flex-col items-end">
                      <span className="text-sm font-bold leading-none">
                        {session.user.name || "Utilisateur"}
                      </span>
                      <span className="text-[10px] font-mono text-muted-fg bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 rounded mt-1 uppercase tracking-wider">
                        {session.user.role}
                      </span>
                    </div>
                    {/* Le bouton de déconnexion est ici */}
                    <LogoutButton />
                  </div>
                ) : (
                  <Link 
                    href="/login"
                    className="text-sm font-medium text-muted-fg hover:text-foreground transition mr-2"
                  >
                    Se connecter
                  </Link>
                )}

                <Link 
                  href="/scan" 
                  className="bg-foreground text-background hover:bg-foreground/90 px-4 py-2 rounded-full text-sm font-bold flex items-center gap-2 transition"
                >
                  <span>🔫</span> <span className="hidden sm:inline">Mode Scan</span>
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {/* --- CONTENU --- */}
        <main className="flex-1">
          {children}
        </main>

      </body>
    </html>
  );
}